plugins {
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

group = 'hr.kn'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '21'
targetCompatibility = '21'

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url "https://repo.clojars.org/" }
    maven { url "https://repository.hellonico.info/repository/hellonico" }
}

dependencies {
    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    // Spring
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }

    // Telegram
    implementation 'com.github.pengrad:java-telegram-bot-api:9.5.0'

    // HTTP client
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.3.1'
    implementation 'org.apache.httpcomponents.core5:httpcore5-reactive:5.3.1'
    implementation 'org.apache.httpcomponents.core5:httpcore5:5.3.1'

    // DJL for YOLOv8
    implementation("ai.djl:api:0.36.0")
    implementation("ai.djl.pytorch:pytorch-engine:0.36.0")
    runtimeOnly "ai.djl.pytorch:pytorch-native-cpu:2.7.1:osx-aarch64"
    runtimeOnly "ai.djl.pytorch:pytorch-native-cpu:2.7.1:linux-x86_64"
    runtimeOnly "ai.djl.pytorch:pytorch-jni:2.7.1-0.36.0"
}

test {
    useJUnitPlatform()
}

bootBuildImage {
    imageName = "${project.group}/${project.name}:${project.version}"
    builder = "paketobuildpacks/builder:tiny" // small image
    environment = [
            BP_JVM_VERSION: '21',
    ]
}
