plugins {
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

group = 'hr.kn'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '21'
targetCompatibility = '21'

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url "https://repo.clojars.org/" }
    maven { url "https://repository.hellonico.info/repository/hellonico" }
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'com.github.pengrad:java-telegram-bot-api:5.0.0'
    implementation 'org.eclipse.jetty:jetty-reactive-httpclient:1.1.4'
    implementation 'org.openpnp:opencv:4.7.0-0'
    implementation 'info.picocli:picocli:4.1.0'
    implementation 'org.scijava:native-lib-loader:2.3.1'
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.3.1'
    implementation 'org.apache.httpcomponents.core5:httpcore5-reactive:5.3.1'
    implementation 'org.apache.httpcomponents.core5:httpcore5:5.3.1'
    implementation 'io.github.rburgst:okhttp-digest:3.0.1'

    // DJL for YOLOv8
    implementation("ai.djl:api:0.36.0")
    implementation("ai.djl.pytorch:pytorch-engine:0.36.0")

    runtimeOnly "ai.djl.pytorch:pytorch-native-cpu:2.7.1:osx-aarch64"
    runtimeOnly "ai.djl.pytorch:pytorch-native-cpu:2.7.1:linux-x86_64"

    runtimeOnly "ai.djl.pytorch:pytorch-jni:2.7.1-0.36.0"

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
}

test {
    useJUnitPlatform()
}
